name: Scanning
on:
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 4 * * 4' # Every Thursday at 04:00
  workflow_dispatch:

jobs:
  scan:
    name: Secrets Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/secret-scanner
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitleaks_license: ${{ secrets.GITLEAKS_LICENSE }}
          gitleaks_regex_internal_url: ${{ secrets.HMCTS_CP_GITLEAKS_REGEX_INTERNAL_URL }}
          gitleaks_regex_banned_ids: ${{ secrets.HMCTS_CP_GITLEAKS_REGEX_BANNED_IDS }}